// tools/gen_manifest.js
// Writes ncm/manifest.lua listing every ported module. Used by ncm/init.lua as a
// fallback when the `fs` API is unavailable (e.g. unit tests off-computer).
'use strict'
const fs = require('fs')
const path = require('path')
const ROOT = '/data/data/com.termux/files/home/netease-ncm-lua'
const dir = path.join(ROOT, 'ncm/module')
const names = fs
  .readdirSync(dir)
  .filter((f) => f.endsWith('.lua'))
  .map((f) => f.replace(/\.lua$/, ''))
  .sort()
const body = names.map((n) => '  ' + JSON.stringify(n)).join(',\n')
fs.writeFileSync(path.join(ROOT, 'ncm/manifest.lua'), '-- Auto-generated by tools/gen_manifest.js. Do not edit by hand.\nreturn {\n' + body + ',\n}\n')
console.log('manifest:', names.length, 'modules')
